# Generated by Django 4.1.2 on 2022-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('base_color', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('ROM', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
                ('display_size', models.CharField(max_length=100)),
                ('num_rear_camera', models.CharField(max_length=100)),
                ('num_front_camera', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('num_of_ratings', models.CharField(max_length=100)),
                ('sales_price', models.CharField(max_length=100)),
                ('discount_percent', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('units_sold', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
